services:
  terraform:
    build:
      context: .
      args:
        WORKDIR: /terraform-test
      dockerfile: Dockerfile
    volumes:
      - ../:/terraform-test
      - ~/.gitconfig:/root/.gitconfig
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    env_file:
      - .docker_env
    container_name: terraform
    tty: true
    platform: linux/x86_64
